### ISSUE TITLE
Enforce a time & timezone offset for all event start_times / end_times.

### ISSUE THREAD

**Issue by janson** [downtowngr/mantle#4] opened 2015-02-26 15:43 UTC
I noticed this with artmuseumgr's Cultural Excursion: Krasl Arts Center and DIA Day Trip events. Because mollusk converts those date/times into unix timestamps on import, it needs the timezone offset.

**Comment by pichot** [comment] 2015-02-26 20:39
What if Mantle returned unix timestamps directly? I could handle timezones internally and return a correct utc timestamp.

**Comment by pichot** [comment] 2015-02-26 21:52
The issue is a bit more complex, actually. Facebook returns only a date for date-only events, like this `"start_time": "2015-07-17"`. This doesn't translate well to using unix timestamps. We could do something like assume any timestamp at midnight is considered an all day event. This could get us in trouble for the occasional event that actually starts at midnight.

Any thoughts on how Mollusk could handle this well?

**Comment by pichot** [comment] 2015-02-26 21:53
I could add another attribute that returns `true` for all day events, which could indicate to Mollusk to handle the `start_time` attribute differently.

**Comment by janson** [comment] 2015-02-27 18:47
Hmmm... all good concerns. If Mantle just returns unix timestamps directly, that'd be easiest/quickest from an import POV. (Especially since the Craft datetime field does assume that a date-only event starts at midnight.) 

That said, one way around that would be to split up start_date and start_time (as well as end_date/end_time) into separate attributes. We can do that on Craft's side pretty easily... which would let us have events that span days with no real time (Art Prize, et. al.) as well as events with specific times. 

Thoughts?

**Comment by pichot** [comment] 2015-04-03 18:04
Does Craft allow an event take place over several days if its `start_time` and `end_time` are both midnight? If it does, I think for simplicity's sake, I can just return timestamps at midnight.

**Comment by pichot** [comment] 2015-04-06 20:05
[addressed by #19]

**Closed as completed by pichot** 2015-04-06 20:05 UTC
